export const AppActionTypes = {
    ADD_INGREDIENT: 'ADD_INGREDIENT',
    REMOVE_INGREDIENT: 'REMOVE_INGREDIENT',
    ADD_FAV: 'ADD_FAV',
    REMOVE_FAV: 'REMOVE_FAV',
    ADD_GROCERY_ITEM: 'ADD_GROCERY_ITEM',
    REMOVE_GROCERY_ITEM: 'REMOVE_GROCERY_ITEM',
    SET_IS_LOADING: 'SET_IS_LOADING',
    GET_RECIPES: 'GET_RECIPES',
    GET_RECIPE_DETAILS: 'GET_RECIPE_DETAILS',
    GET_SUGGESTIONS: 'GET_SUGGESTIONS'
}